name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Install dependencies & build
        working-directory: ./web
        run: yarn install & yarn build
