name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: web
          cmd: install

      - name: Build
        working-directory: web
        run: yarn build
