name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: web
          cmd: install

      - name: Lint code
        working-directory: web
        run: yarn lint

      - name: Build app
        working-directory: web
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENTID: ${{ secrets.AUTH0_CLIENTID }}
        run: yarn build

      - name: Deploy app
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: web/build

  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore
        working-directory: api
        run: dotnet tool restore && dotnet restore

      - name: Unit Test
        working-directory: api
        run: dotnet test

      - name: Lint code
        working-directory: api
        run: dotnet csharpier . --check

      - name: Publish
        working-directory: api
        run: dotnet publish -c Release -o out

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: urls-prod-api
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "./api/out"

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Login to registry
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Build and push to registry
      #   working-directory: api
      #   run: |
      #     docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:prod-${{ github.sha }}
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:prod-${{ github.sha }}

      # - name: Deploy image to app service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: urls-prod-api
      #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      #     images: "${{ secrets.REGISTRY_LOGIN_SERVER }}/api:prod-${{ github.sha }}"
