name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: web
          cmd: install

      - name: Build app
        working-directory: web
        run: yarn build

      - name: Deploy app
        uses: Azure/static-web-apps-deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: web/build
